-- Auto-generated from schema-map-postgres.yaml (map@sha1:6D9B52237D942B2B3855FD0F5500331B935A7C62)
-- engine: postgres
-- table:  audit_chain

CREATE TABLE IF NOT EXISTS audit_chain (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  audit_id BIGINT NOT NULL,
  chain_name VARCHAR(100) NOT NULL DEFAULT 'default',
  prev_hash BYTEA NULL,
  hash BYTEA NOT NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT uq_audit_chain UNIQUE (audit_id)
);
